app_one/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "app_one"

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^special/$', views.special, name='user_special'),
]

ready_project_three/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('app_one.urls')),
    url(r'$', views.index, name='index'),
]

app_one/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        # built-in attribute of django.contrib.auth.User

        return self.user.username

app_one/forms.py
from django import forms
from django.contrib.auth.models import User
from app_one.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

app_one/views.py
from django.shortcuts import render

from .forms import UserForm, UserProfileInfoForm

# Create your views here.

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'app_one/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


@login_required
def special(request):
    return HttpResponse('Something special')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active.')
        else:
            print('Someone tried to login and failed!')
            print('Username: {} and password {}'.format(username, password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'app_one/login.html', {})

ready_project_three/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):

    index_dict = {'title': 'Home Page'}
    return render(request, 'index.html', context=index_dict)

templates/app_one/login.html
{% extends 'base.html' %}

{% block bodyblock %}
<div class="jumbotron">
    <h1 class="display-3">Login</h1>
    <p class="lead">Please log in.</p>
    <hr class="my-2">
    <p>More info</p>

    <form action="{% url 'app_one:user_login'%}" method="post">
        {% csrf_token %}
        <label for="username"></label>
        <input type="text" name="username" id="" placeholder="Enter Username">
        <label for="password"></label>
        <input type="password" name="password" id="">

        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock bodyblock %}

templates/app_one/registration.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block bodyblock %}

<div class="jumbotron">
    <h1 class="display-3">Registration</h1>
    <p class="lead">Enter your information</p>
    <hr class="my-2">


    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}

    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    {% endif %}
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" name="" value="Register">
    </form>

    <p class="lead">
        <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Jumbo action name</a>
    </p>
</div>


{% endblock bodyblock %}

templates/base.html
<!doctype html>
<html lang="en">

    <head>
        <title></title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Home</a>
            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_one:register' %}">Register</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_one:user_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_one:user_login' %}">Login</a>
                    </li>
                    {% endif %}

                    {% comment %} <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="#">Action 1</a>
                            <a class="dropdown-item" href="#">Action 2</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> {% endcomment %}
            </div>
        </nav>


        <div class="container">
            {% block bodyblock %}
            {% endblock bodyblock %}
        </div>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block bodyblock %}

<div class="jumbotron">
    <h1 class="display-3">Django Level 5</h1>
</div>


{% endblock bodyblock %}